### ISSUE TITLE
files in subdirectories

### ISSUE THREAD

**Issue by stockf** [derberg/copy-files-to-other-repositories#35]
This is somewhere in between a bug and a feature request.

#### Describe the bug
It's not possible to have the files to copy over in a subdirectory but copy it to a different directory.

#### How to Reproduce
- Create a subdirectory `workflows-a` with a file `action.yml`
- Try Reference it in the action with 
```
patterns_to_include: 'workflows-a/action.yml'
destination: '.github/workflows'
```
Or
```
patterns_to_include: 'workflows-a/*'
destination: '.github/workflows'
```
- The action will copy the output to `.github/workflows/workflows-a/action.yml` (example 1) or do nothing (example 2)

#### Expected behavior
I would expect that it is possible to group my actions in a subdirectory and have them copied to a different directory. E.g. when I have two different `dependabot.yml` configurations for projects of type `A` and `B`. The filename is also preserved, so currently it is impossible to service this use case.

**Comment by derberg** [comment]
Hey, I described in docs that `patterns_to_include` works based on `include` function, so you can just provide folder name like `patterns_to_include: 'workflows-a'`

but yeah `.github/workflows/workflows-a/action.yml` is definitely a bug, thanks!

**Comment by derberg** [comment]
it is fixed with latest
