### ISSUE TITLE
Ability to generate or update a report on compliance with expectations

### ISSUE THREAD

**Issue by Relequestual** [derberg/copy-files-to-other-repositories#42]
#### Reason/Context
Please try answering few of those questions
**- Why we need this improvement?**
There's no easy way to see all the pending PRs that need to be merged in order for the expectations to be met.

**- How will this change help?**
A report generated in some format, or having a GH org wide Project containing all the PRs would give an immediate view of what PR merging work is to be done.

**- What is the motivation?** 
In considering how we (JSON Schema) might use this tool, I was concerned that it might become easy to loose track of compliance with the expectations defined in the action config. How do you currently manage this with the AsyncAPI org?

#### Description
Please try answering few of those questions
**- What changes have to be introduced?**
Would need a way to determine outstanding PRs that were created by the tool across repos which should be compliant according to the expectations.

**- Will this be a breaking change?**
Nope

**- How could it be implemented/designed?**
I don't know if actions can be triggered based on hooks or actions in other repos. I'd guess not.
As such, when a PR is created, a scheduled action should be created to regulallay check the status of pending PRs which the tool authored.

**Comment by derberg** [comment]
@Relequestual good questions

The purpose of this action is to copy files from one repo to multiple others. Not monitor if "the copy operation" was successful.

To have a kind of assurance if PRs are merged, at AsyncAPI, we have 2 additional workflows (they are copied to all the repos):
- [automerge.yml](https://github.com/asyncapi/.github/blob/master/.github/workflows/automerge.yml) that automatically approves and merges PR submitted by our AsyncAPI bot. One bot opens PR to update workflows, and another bot approves and merges 😄 
- [automerge-orphans.yml](https://github.com/asyncapi/.github/blob/master/.github/workflows/automerge-orphans.yml) timeouts are common, especially if there are some complex tests. So happened in the past few times, not many, that automerge failed. So there were PRs hanging forever, until someone noticed by accident. This is why we have this workflow for orphans. It checks every day, midnight, if there are some PRs created by the bot, but not merged. If there are not merged PRs, a message in slack is dropped
  <img width="538" alt="Screenshot 2022-09-01 at 20 34 05" src="https://user-images.githubusercontent.com/6995927/187987517-f227f795-833e-47c8-bfd3-b0e53d70b88b.png">

Does that answer your question?

**Comment by derberg** [comment]
@Relequestual I'm assuming you are ok with the answer. Closing, otherwise ping me if some more clarification is needed
